#ifndef R3BFrsReader_H
#define R3BFrsReader_H

#include "R3BReader.h"

class TClonesArray;
class FairLogger;

struct EXT_STR_h101_FRS_t;
typedef struct EXT_STR_h101_FRS_t EXT_STR_h101_FRS;


/**
 * A reader of FRS data with UCESB.
 * Receives mapped raw data and converts it to R3BRoot objects.
 * @author J.L. Rodriguez
 * @since July 29, 2018
 */
class R3BFrsReader : public R3BReader {
   public:
   /**
    * Standard constructor.
    * Creates instance of the reader. To be called in the steering macro.
    * @param Pointer to a full C structure generated by the Ucesb unpacker.
    */
   R3BFrsReader(EXT_STR_h101_FRS *, UInt_t);
   ~R3BFrsReader();

   Bool_t Init(ext_data_struct_info *);
   Bool_t Read();
   void Reset();

   /** Accessor to select online mode **/
   void SetOnline(Bool_t option){fOnline=option;} 

   private:
   /* An event counter */
   unsigned int fNEvent; 
   /* Reader specific data structure from ucesb */
   EXT_STR_h101_FRS* fData;
   /* Data offset */
   UInt_t fOffset;
   /* FairLogger */
   FairLogger*     fLogger;

   Bool_t fOnline;//Don't store data for online

   TClonesArray* fArray;     // Output array for frs scin and scalers.
   TClonesArray* fArrayMusic;// Output array for music detectors.
   TClonesArray* fArrayTpc;  // Output array for tpc detectors. 

   public:
	ClassDef(R3BFrsReader, 0);
};

#endif
