#ifndef R3BFrsReader_H
#define R3BFrsReader_H

#include "R3BReader.h"
#include "TFile.h"
#include "TTree.h"

class TClonesArray;
class FairLogger;
class TLeaf;
class R3BEventHeader;

struct EXT_STR_h101_FRS_t;
typedef struct EXT_STR_h101_FRS_t EXT_STR_h101_FRS;
//class ext_data_struct_info;

/**
 * A reader of AMS data with UCESB.
 * Receives mapped raw data and converts it to R3BRoot objects.
 * @author J.L. Rodriguez
 * @since May 12, 2018
 */
class R3BFrsReader : public R3BReader {
	public:
		/**
		 * Standard constructor.
		 * Creates instance of the reader. To be called in the steering macro.
		 * @param Pointer to a full C structure generated by the Ucesb unpacker.
		 */
		R3BFrsReader(EXT_STR_h101_FRS *, UInt_t);
		~R3BFrsReader();

		Bool_t Init(ext_data_struct_info *);
		Bool_t Read();
		void Reset();

  /** Accessor to select online mode **/
  void SetOnline(Bool_t option){fOnline=option;} 

	private:
		/* An event counter */
		unsigned int fNEvent;
		/* Reader specific data structure from ucesb */
		EXT_STR_h101_FRS* fData;
		/* Data offset */
		UInt_t fOffset;
		/* FairLogger */
		FairLogger*     fLogger;
		/* A pointer to the R3BEventHeader structure */
		R3BEventHeader* fEventHeader;

  Bool_t fOnline;//Don't store data for online

	  TClonesArray* fArray;     // Output array for frs scin and scalers.
	  TClonesArray* fArrayMusic;// Output array for music detectors.
	  TClonesArray* fArrayTpc;  // Output array for tpc detectors.
	  TClonesArray* fArrayMw;   // Output array for mw detectors. 

  int unpack_vme0[21][32];
  int unpack_vme1[21][32];
  float by_pos_TPC1,anal_de_cor2;

  TBranch        *b_theData_unpack_vme0;   //!
  TBranch        *b_theData_unpack_vme1;   //!

  TFile *fRootFile;
  TTree* fTreeFile;

  Int_t tpc_ae[4],  tpc_le[2],  tpc_re[2],  tpc_dt[4],  tpc_lt[2], tpc_rt[2];

	public:
		ClassDef(R3BFrsReader, 0);
};

#endif
